version: '3.8'
services:
  shareit-gateway:
    build: shareIt-gateway
    container_name: gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - shareit-server
    environment:
      - SHAREIT_SERVER_URL=http://shareIt-server:9090

  shareit-server:
    build: shareIt-server
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share_it
      - POSTGRES_USER=share_root
      - POSTGRES_PASSWORD=root

  db:
    image: postgres:13.8-alpine
    container_name: postgresql_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=share_it
      - POSTGRES_USER=share_root
      - POSTGRES_PASSWORD=root